apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-consilium
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  labels:
    name: productconsilium
spec:
  project: default
  source:
    repoURL: 'https://github.com/mhw29/product_consilium_infra.git'
    path: kubernetes/overlays/dev
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: productconsilium
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
