resources:
- ../../base

replicas:
- name: product-consilium-deployment
  count: 2
images:
- name: productconsilium.azurecr.io/productconsilium
  newTag: fad77070391324e3d5bf38dca41dec6537f8e13c
namePrefix: dev-