apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-consilium-deployment
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: productconsilium.azurecr.io/productconsilium:78cc7a033b364ccd06dcc95c1f63ee19e950e5f1
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: productconsilium-externalsecrets
              key: postgresPassword
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: productconsilium-externalsecrets
              key: postgresUser
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_DB_NAME
          valueFrom:
            secretKeyRef:
              name: productconsilium-externalsecrets
              key: postgresDBName
        - name: POSTGRES_PORT
          value: "5432"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        

