apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: productconsilium-externalsecrets
  namespace: productconsilium # Replace with the actual namespace if different
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    kind: SecretStore
    name: azure-backend
  target:
    name: productconsilium-externalsecrets
    creationPolicy: Owner
  data:
    - secretKey: postgresPassword
      remoteRef:
        key: postgres-password
