apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
      listen 80;
      server_name ~^(.+)$;

      location = /favicon.ico { 
        access_log off; 
        log_not_found off; 
      }

      location /static/ {
        root /app/product_consilium; 
      }

      location /healthcheck {
        return 200 "Server is healthy";
      }    

      location / {
        include proxy_params;
        proxy_set_header Origin $http_origin;
        proxy_pass http://productconsilium-service:80; # Adjust the port if Django listens on a different one
      }
    }
