apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-volume
  namespace: productconsilium
  labels:
    type: local
    app: nginx
spec:
  storageClassName: managed-csi
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /app/product_consilium/static