apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: productconsilium
data:
  default.conf: |
    server {
      listen 80;

      location /static/ {
        root /app/product_consilium; 
        autoindex on;  # Optional: Enables directory listing
        expires max;   # Optional: Sets expiration for static content
      }

      location = /favicon.ico { 
        access_log off; 
        log_not_found off; 
      }

      location /healthcheck {
        return 200 "Server is healthy";
      }
    }
