apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-consilium-ingress
  namespace: productconsilium
  annotations:
    external-dns.alpha.kubernetes.io/hostname: dev-app.productconsilium.com
    cert-manager.io/cluster-issuer: letsencrypt-production
    cert-manager.io/acme-challenge-type: http01
spec:
  tls:
  - hosts:
    - dev-app.productconsilium.com
    secretName: tls-secret
  ingressClassName: "nginx"  # This replaces the deprecated annotation
  rules:
  - host: dev-app.productconsilium.com
    http:
      paths:
      - path: /static
        pathType: Prefix
        backend:
          service:
            name: productconsilium-nginx-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: productconsilium-service
            port:
              number: 80
