apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'postgres:14'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: productconsilium-externalsecrets
                key: postgresPassword
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: productconsilium-externalsecrets
                key: postgresUser
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: productconsilium-externalsecrets
                key: postgresDBName
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
          # resources:
          #   limits:
          #     cpu: "1"
          #     memory: "1Gi"
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim