apiVersion: v1
kind: Secret
metadata:
  name: productconsilium
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/mhw29/product_consilium_infra.git