apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity 
    userAssignedIdentityID: 43bdea3b-e320-4ca4-8ee6-e392118e38e3  
    keyvaultName: productconsiliumkv
    cloudName: "AzurePublicCloud"                  
    objects:  |
      array:
        - |
          objectName: postgres-password
          objectType: secret
    tenantId: 5d0cf079-c27d-46d5-b473-ec54a6307720
    