apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity 
    userAssignedIdentityID: 1113f491-08a5-4c01-b555-12f3333d09ea  
    keyvaultName: productconsiliumkv
    cloudName: "AzurePublicCloud"                  
    objects:  |
      array:
        - |
          objectName: postgres-password
          objectType: secret
    tenantId: 5d0cf079-c27d-46d5-b473-ec54a6307720
    