apiVersion: v1
kind: Service
metadata:
  name: productconsilium-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: dev-app.productconsilium.com
spec:
  type: LoadBalancer
  selector:
    app: productconsilium-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
