apiVersion: v1
kind: Service
annotations:
  external-dns.alpha.kubernetes.io/hostname: dev-app.productconsilium.com
metadata:
  name: productconsilium-service
spec:
  type: LoadBalancer
  selector:
    app: productconsilium-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
